supported_currencies = {
    "AUD": "$",
    "BGN": "BGN",
    "BRL": "R$",
    "CAD": "$",
    "CHF": "Fr.",
    "CNY": "¥",
    "CZK": "Kč",
    "DKK": "Kr",
    "EUR": "€",
    "GBP": "£",
    "HKD": "HK$",
    "HRK": "kn",
    "HUF": "Ft",
    "IDR": "Rp",
    "ILS": "₪",
    "INR": "₹",
    "ISK": "kr",
    "JPY": "¥",
    "KRW": "W",
    "MXN": "$",
    "MYR": "RM",
    "NOK": "kr",
    "NZD": "NZ$",
    "PHP": "₱",
    "PLN": "zł",
    "RON": "L",
    "RUB": "R",
    "SEK": "kr",
    "SGD": "S$",
    "THB": "฿",
    "TRY": "TRY",
    "USD": "US$",
    "ZAR": "R",
}

storage_name = "exchange_rates"
